---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns -n
  labels:
    name: fortune
    version: v1
spec: 
  containers:
  - name: fortune-container
    image: maxchong29/myfortuneapp:v1
    imagePullPolicy: Always
    env:
      - name: APP_PORT
        value: "3000"
    ports:
      - name: http
        containerPort: 3000 