---
apiVersion: v1
kind: Namespace
metadata: 
  name: mynwdb
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwdb-config
  namespace: mynwdb
#helloworld
data:
  db_password: changeit  

---
apiVersion: v1
kind: Secret
metadata:
  name: nwdbsecret
  namespace: mynwdb
#changeit #Y2hhbmdlaXQ= 
data:
  db_password: aGVsbG93b3JsZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  namespace: mynwdb
  labels:
    name: nwdb
    version: v2
spec:
  # number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: nwdb
      version: v2
  template:
    # pod template
    metadata:
      name: nwdb-pod
      labels:
        name: nwdb
        version: v2
    spec: 
      containers:
      - name: nwdb-container
        image: maxchong29/mynorthwindapp:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwdbsecret
              key: db_password
        - name: APP_PORT
          value: "3306"
        ports:
        - name: mysql-port
          containerPort: 3306


