---
apiVersion: v1
kind: Namespace
metadata: 
  name: mynw
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwdb-config
  namespace: mynw
data:
  db_host: nwdb-svc.mynw.svc.cluster.local
  db_user: root      

---
apiVersion: v1
kind: Secret
metadata:
  name: nwdbsecret
  namespace: mynw
#changeit #Y2hhbmdlaXQ=
#helloworld aGVsbG93b3JsZA== 
data:
  db_password: aGVsbG93b3JsZA==