---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  namespace: mynw
  labels:
    name: nwdb
    version: v2
spec:
  # number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: nwdb
      version: v2
  template:
    # pod template
    metadata:
      name: nwdb-pod
      labels:
        name: nwdb
        version: v2
    spec: 
      containers:
      - name: nwdb-container
        image: maxchong29/mynorthwindapp:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwdbsecret
              key: db_password        
        - name: APP_PORT
          value: "3306"
        ports:
        - name: mysql-port
          containerPort: 3306

---
apiVersion: v1 
kind: Service 
metadata:
  name: nwdb-svc
  namespace: mynw
  labels:
    name: nwdb-svc
    version: v1
spec:
  type: ClusterIP
  selector: 
    name: nwdb
    version: v2
  ports:
    - name: http
      port: 3306
      targetPort: mysql-port


