apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapp
spec:
  selector:
    matchLabels:
      app: wapp
  template:
    metadata:
      labels:
        app: wapp
    spec:
      containers:
      - name: wapp
        image: stackupiss/weather:v1
        env:
          - name: "APP_ID"
            value: "db1001a1d883cc9f307fe5e49228dcab"
          - name: "APP_DEFAULT_CITY"
            value: "singapore"  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: w-svc
spec:
  selector:
    app: wapp
  ports:
  - port: 80
    targetPort: 3000
